version: "3.9"
services:
  backend:
    build:
      context: ./garden_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/garden_db
      - JWT_SECRET=your-jwt-secret
    depends_on:
      - mongo

  frontend:
    build:
      context: ./garden_frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
